# learning_log
Python3.6 Django2.2
项目：《Python编程从入门到实践》------部署“学习笔记”
进度：编写到 new_entry 部分，无法显示出来，代码全部正确
错误原因：
Reverse for ' new_entry' not found. ' new_entry' is not a valid view function or pattern name.
Request Method:	GET
Request URL:	http://localhost:8000/topics/(%3FP2%5Cd+)/
Django Version:	2.2.3
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for ' new_entry' not found. ' new_entry' is not a valid view function or pattern name.
Exception Location:	C:\Users\Administrator\work\item\11_env\lib\site-packages\django\urls\resolvers.py in _reverse_with_prefix, line 668
Python Executable:	C:\Users\Administrator\work\item\11_env\Scripts\python.exe
Python Version:	3.7.0
Python Path:	
['C:\\Users\\Administrator\\work\\item\\learning_log',
 'C:\\Program Files (x86)\\CambridgeSoft\\ChemOffice2015\\ChemScript\\Lib',
 'C:\\Users\\Administrator\\work\\item\\11_env\\Scripts\\python37.zip',
 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\DLLs',
 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\lib',
 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32',
 'C:\\Users\\Administrator\\work\\item\\11_env',
 'C:\\Users\\Administrator\\work\\item\\11_env\\lib\\site-packages']
Server time:	Thu, 18 Jul 2019 13:00:50 +0000
